[theme]

# Primary accent for interactive elements
primaryColor="#d33682"

# Background color for the main content area
backgroundColor="#002b36"

# Background color for sidebar and most interactive widgets
secondaryBackgroundColor="#586e75"

# Color used for almost all text
textColor="#fafafa"

# Font family for all text in the app, except code blocks
# Accepted values (serif | sans serif | monospace) 
# Default: "sans serif"
font="sans serif"


[deprecation]
showPyplotGlobalUse = false






